// Automatically generated by MockGen. DO NOT EDIT!
// Source: testContext.go

package mocks

import (
	"testing"

	gomock "github.com/golang/mock/gomock"
)

// Mock of testContext interface
type MocktestContext struct {
	ctrl     *gomock.Controller
	recorder *_MocktestContextRecorder
}

// Recorder for MocktestContext (not exported)
type _MocktestContextRecorder struct {
	mock *MocktestContext
}

func GetMock(t *testing.T) *MocktestContext {
	mockCtrl := gomock.NewController(t)
	defer mockCtrl.Finish()
	return NewMocktestContext(mockCtrl)
}

func NewMocktestContext(ctrl *gomock.Controller) *MocktestContext {
	mock := &MocktestContext{ctrl: ctrl}
	mock.recorder = &_MocktestContextRecorder{mock}
	return mock
}

func (_m *MocktestContext) EXPECT() *_MocktestContextRecorder {
	return _m.recorder
}

func (_m *MocktestContext) Errorf(format string, args ...interface{}) {
	_s := []interface{}{format}
	for _, _x := range args {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Errorf", _s...)
}

func (_mr *_MocktestContextRecorder) Errorf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0}, arg1...)
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Errorf", _s...)
}
